language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.2.2
  - 2.3.1
  - rbx-2
  - rbx
  - jruby-9.1.4.0
jdk:
  - openjdk7
script: bundle exec rake test
env:
  matrix:
    - DEVISE_ORM=active_record
    - DEVISE_ORM=mongoid
gemfile:
  - Gemfile
  - gemfiles/Gemfile.devise-4.0
  - gemfiles/Gemfile.devise-4.1
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=active_record
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-master
      env: DEVISE_ORM=mongoid
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-master
#    - rvm: jruby-19mode
#      gemfile: gemfiles/Gemfile.rails-3.2.x
#      env: DEVISE_ORM=mongoid
