language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.2.2
  - rbx-2
  - jruby-9.0.5.0
script: bundle exec rake test
env:
  - DEVISE_ORM=active_record
  - DEVISE_ORM=mongoid
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.r4.devise-3.2
  - Gemfile
install: "travis_retry bundle install"
services:
  - mongodb
matrix:
  include:
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile.devise-master
      env: DEVISE_ORM=active_record
  allow_failures:
    - gemfile: gemfiles/Gemfile.devise-master
#  exclude:
#    - rvm: jruby-19mode
#      gemfile: gemfiles/Gemfile.rails-3.2.x
#      env: DEVISE_ORM=active_record
#    - rvm: jruby-19mode
#      gemfile: gemfiles/Gemfile.rails-3.2.x
#      env: DEVISE_ORM=mongoid
